spring.data.mongodb.auto-index-creation=false

logging.level.root=INFO
logging.level.org.springframework.security=WARN
logging.level.org.springframework.data.mongodb.core.MongoTemplate=WARN
logging.level.com.gymhelper=INFO
