server.port=4000
spring.mongodb.uri=mongodb+srv://admin:MlDYA85ab6sBMDPM@liftorium.f4ydbnk.mongodb.net/gym_helper?retryWrites=true&w=majority&appName=Liftorium
spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.boot.context.config=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.com.gymhelper=DEBUG

app.cors.allowed-origin=http://localhost:4200
app.jwt.access-secret=replace-with-a-long-random-access-secret
app.jwt.refresh-secret=replace-with-a-long-random-refresh-secret
app.jwt.access-token-ttl=15m
app.jwt.refresh-token-ttl=30d
app.jwt.refresh-token-cookie-name=${REFRESH_TOKEN_COOKIE_NAME:gym_refresh_token}
app.jwt.refresh-token-cookie-path=/api/v1/auth
