server.port=${PORT}
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=false

logging.level.root=INFO
logging.level.org.springframework.security=WARN
logging.level.org.springframework.data.mongodb.core.MongoTemplate=WARN
logging.level.com.gymhelper=INFO

app.cors.allowed-origin=${CORS_ORIGIN}
app.jwt.access-secret=${JWT_ACCESS_SECRET}
app.jwt.refresh-secret=${JWT_REFRESH_SECRET}
app.jwt.access-token-ttl=${ACCESS_TOKEN_TTL}
app.jwt.refresh-token-ttl=${REFRESH_TOKEN_TTL}
app.jwt.refresh-token-cookie-name=${REFRESH_TOKEN_COOKIE_NAME}
app.jwt.refresh-token-cookie-path=/api/v1/auth
